name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # This is necessary for the peaceiris/actions-gh-pages to work

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory containing your HTML/CSS/JS files; adjust if your files are in a subdirectory like './public'
