name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js 14.x; adjust as necessary based on your requirements

      - name: Install dependencies
        run: npm install  # Install npm dependencies

      - name: Configure Git
        run: |
          git config --local user.email "abdullah_2001@live.com"
          git config --local user.name "AbdullahK047"
        # Replace "you@example.com" with your GitHub email and "Your Name" with your GitHub username or any name you prefer

      - name: Build and deploy
        env:
          CI: false  # Set CI environment variable to false
        run: npm run deploy  # This runs the build script and then deploys to gh-pages using your deploy script

      - name: Clean up post-deployment
        run: rm -rf node_modules/  # Optional step to clean up workspace post deployment
